### ISSUE TITLE
TITULO:  Explicacion de la idea del sitio

### ISSUE THREAD

**Issue by djarksham** [conpantuflas/proyecto_final#18]
COMO:  En la pantalla de inicio debe mostrarse una explicacion del funcionamiento de este

PUEDO: Ver cexplicacion de como funciona el sitio

PARA: Que el usuario pueda entender

Criterio de aceptación:
- Explicacion visible al inicio del sitio de como funciona este.

**Comment by fixmaspe** [comment]
Se hizo el logo, enlaces del encabezado de la pagina, y colores, según acordamos en equipo
